name: Telegram Notifications

on:
  push:
  create:
  delete:
  release:
    types: [published]

jobs:
  telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Send Telegram Message
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        run: |

          if [ "${{ github.event_name }}" = "push" ]; then

            FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)

            MESSAGE="🚀 NEW PUSH
Repository: ${{ github.repository }}
User: ${{ github.actor }}
Branch: ${{ github.ref_name }}
Commit: ${{ github.event.head_commit.message }}
Files:
$FILES
URL:
${{ github.event.head_commit.url }}"

          elif [ "${{ github.event_name }}" = "create" ]; then

            MESSAGE="🌱 CREATED
User: ${{ github.actor }}
Type: ${{ github.event.ref_type }}
Name: ${{ github.event.ref }}"

          elif [ "${{ github.event_name }}" = "delete" ]; then

            MESSAGE="🗑 DELETED
User: ${{ github.actor }}
Type: ${{ github.event.ref_type }}
Name: ${{ github.event.ref }}"

          elif [ "${{ github.event_name }}" = "release" ]; then

            MESSAGE="🏷 RELEASE
Tag: ${{ github.event.release.tag_name }}
URL:
${{ github.event.release.html_url }}"

          fi


          curl -X POST \
          "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
          -d chat_id="${CHAT_ID}" \
          --data-urlencode text="$MESSAGE"